name: 'setup-env'
on:
  pull_request:
    paths:
    - 'setup-env/**'
    - '.github/workflows/setup-env*'
  push:
    paths:
    - 'setup-env/**'
    - '.github/workflows/setup-env*'


jobs:
  unit-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 16.x
      uses: actions/setup-node@master
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: 'setup-env/package-lock.json'

    - name: npm install
      working-directory: ./setup-env
      run: npm install

    - name: Lint and Unit tests
      working-directory: ./setup-env
      run: npm run test
